### PR TITLE
Pavel/cor 1675 shake to report

### PR DESCRIPTION
**Pull request by PavelKurzo**
All right, while testing i found a new issue which was fixed, when having 2 instances of SpyButton was causing an error, when it is presented with shake, then it was not opening correctly with a button, was instantly dismissing on the first open. 

To test and make it work in the application, i'm using the code for onShake in the app (main file), not in the package, and checking if it is already presented or not, and only then we show on shake. By clicking button it is working as it was. Code sample to test:

[ShowOnSHakeApp.swift.zip](https://github.com/user-attachments/files/15859641/ShowOnSHakeApp.swift.zip)

What could be interesting is to handle the on shake logic inside of the package, theoretically it could work, because we still gonna use SpyButton in the main file.

### CODE REVIEW

**Comment by PavelKurzo** [comment]
I was right and my idea is working, but not that good as i thought. I moved the onShake logic inside the package, and weird behaviour can appear if the user is opening the sheet to fast, first via shake, after closing with a button, and i guess that the presentation is not over, and it is instantly dismissing. And after some testing the button can stop working after presenting it with both ways, you need to go back and reopen view

**Comment by PavelKurzo** [comment]
Some updated, i find out that when we use SpyButton a few times it is not working as expected, can dismiss itself right after the user first time clicks on the button, after it is working okay. How to fix it i've got no ideas for now, but will try more later. I guess all my ideas now are similar and not working

**Comment by PavelKurzo** [comment]
Woooooorking! Ahaha. After 50 commits i managed to solve the issue with presenting. Now there is no need to add any extra spy button to make the shake work. We can have only one, and in the application whenever user shake, we show this sheet. The yellow warn is still there "Presenting view controller <_TtGC7SwiftUI29PresentationHostingControllerVS_7AnyView_: 0x109013000> from detached view controller", but for me everything is good. Idk if i can come up with smt else.

**Comment by bereydev** [comment]
@PavelKurzo I updated your PR to make onShake a separate feature.
I also added Keychain management for the API key in prevision of the release, cause passing it as a parameter is really unsafe.

In the end you see that the code got quite simplified and it is not possible to activate onShake feature from any page and separately from the SpyBug Button. It becomes the clearer, more secure and let the choice to the user. For more info refer to the updated readme

**Pull request merged**
